// adsr_helper.js
// Max JavaScript object that formats ADSR values as:
// 0., 1., A, S, D, 0., R
// GENERATED BY LUMO CUZ WHY THE FUCK IS THIS SO HARD TO DO IN NATIVE MAX!!!!!!

// -------------------------------------------------
// Global variables – store the latest values
var attack  = 0.;   // inlet 1
var decay   = 0.;   // inlet 2
var sustain = 0.;   // inlet 3
var release = 0.;   // inlet 4

// -------------------------------------------------
// Set the number of inlets/outlets
// 5 inlets: bang + A + D + S + R
// 1 outlet: the formatted list
inlets = 5;
outlets = 1;

// -------------------------------------------------
// Helper to output the list in the required format
function outputList() {
    // Build the list exactly as requested
    var lst = [
        0.,          // leading 0.
        1.,
        1.,          // leading 1.
        attack,      // A
        sustain,     // S (note the swapped order)
        decay,       // D
        0.,          // middle 0.
        release      // R
    ];
    outlet(0, lst);
}

// -------------------------------------------------
// Inlet 0 – bang triggers the output
function bang() {
    if (this.inlet === 0) {
        outputList();
    }
}

// -------------------------------------------------
// Inlet 1 – receive Attack value
function msg_float(v) {
    // Max calls the same function for all numeric messages,
    // so we dispatch based on which inlet the message came from.
    switch (this.inlet) {
        case 1: attack  = v; break;
        case 2: decay   = v; break;
        case 3: sustain = v; break;
        case 4: release = v; break;
        default: break; // ignore anything else
    }
}

// Also accept integers (they are converted to float automatically)
function msg_int(v) { msg_float(v); }

// -------------------------------------------------
// Optional: clear all stored values (helpful for testing)
function clear() {
    attack = decay = sustain = release = 0.;
}

// -------------------------------------------------
// Assistance strings – shown when the user hovers over the object
setinletassist(0, "bang → output formatted list");
setinletassist(1, "float/int – Attack (A)");
setinletassist(2, "float/int – Decay (D)");
setinletassist(3, "float/int – Sustain (S)");
setinletassist(4, "float/int – Release (R)");

setoutletassist(0, "list: 0., 1., A, S, D, 0., R");